#====================================================================
# File automatically generated by ES3  
# This file regenerated each time you run EISC Studio, so save under a 
# new name if you hand edit, or it will be overwritten.
#				www.adc.co.kr
#====================================================================



ECHO	=	echo.exe
CC	=	ae32000-elf-gcc
AS	=	ae32000-elf-as
LD	=	ae32000-elf-ld
AR	=	ae32000-elf-ar
OBJCOPY	=	ae32000-elf-objcopy
OBJDUMP	=	ae32000-elf-objdump
CFLAGS	=	 -O2  -g -fno-strength-reduce -Wundef -Wall 
ASFLAGS	=	 -gstabs 
LDFLAGS	=	-Wall -nostartfiles -lgcc -lc -lm
DISFLAGS	=	-dzShxl
ARFLAGS	=	rcusv
#====== Directory =====
OUTPUTDIR	=	output/
OBJDIR	=	output/obj/
INCDIR	=	\
	 -I"App"\
	 -I"CMOS"\
	 -I"Common"\
	 -I"Devices/EX-SDI"\
	 -I"Devices/FPGA"\
	 -I"Devices/HDMI/ITE6615"\
	 -I"Devices/HDMI/IT66121"\
	 -I"Devices/HDMI/IT6802"\
	 -I"Devices/HDMI/LT8618"\
	 -I"Devices/HDMI/LT8619C"\
	 -I"Devices/HDMI/PS8409"\
	 -I"Devices/HDMI/SIL9136"\
	 -I"Devices/PLL"\
	 -I"Devices/TVI"\
	 -I"Drivers"\
	 -I"Graphic"\
	 -I"LENS"\
	 -I"Lucida/include"\
	 -I"Protocol"\
	 -I"Video"
LIBDIR	=	
LIBS	=	

SOURCES	 += App/app_3a.c
SOURCES	 += App/app_4k60.c
SOURCES	 += App/app_initial.c
SOURCES	 += App/app_pano.c
SOURCES	 += App/app_cascade_cam.c
SOURCES	 += App/app_picture_style.c
SOURCES	 += App/app_lowlight_control.c
SOURCES	 += App/app_sync_lock.c
SOURCES	 += App/main.c
SOURCES	 += CMOS/ar0134.c
SOURCES	 += CMOS/ar0331.c
SOURCES	 += CMOS/cmos_if.c
SOURCES	 += CMOS/imx076.c
SOURCES	 += CMOS/imx124.c
SOURCES	 += CMOS/imx252.c
SOURCES	 += CMOS/imx265.c
SOURCES	 += CMOS/imx253.c
SOURCES	 += CMOS/imx273.c
SOURCES	 += CMOS/imx136.c
SOURCES	 += CMOS/imx174.c
SOURCES	 += CMOS/imx178.c
SOURCES	 += CMOS/imx185.c
SOURCES	 += CMOS/imx222.c
SOURCES	 += CMOS/imx226.c
SOURCES	 += CMOS/imx274.c
SOURCES	 += CMOS/imx238.c
SOURCES	 += CMOS/imx290.c
SOURCES	 += CMOS/imx385.c
SOURCES	 += CMOS/imx334.c
SOURCES	 += CMOS/imx326.c
SOURCES	 += CMOS/mn34041.c
SOURCES	 += CMOS/mn34220.c
SOURCES	 += CMOS/mn34420.c
SOURCES	 += CMOS/mt9m131.c
SOURCES	 += CMOS/mt9p031.c
SOURCES	 += CMOS/ov2710.c
SOURCES	 += CMOS/po3100k.c
SOURCES	 += CMOS/ps1210k.c
SOURCES	 += CMOS/ps1400k.c
SOURCES	 += Common/cmdproc.c
SOURCES	 += Common/cmds.c
SOURCES	 += Common/delay.c
SOURCES	 += Common/i2c.c
SOURCES	 += Common/init.c
SOURCES	 += Common/ir.c
SOURCES	 += Common/isr.c
SOURCES	 += Common/key.c
SOURCES	 += Common/msg.c
SOURCES	 += Common/serial.c
SOURCES	 += Common/spi.c
SOURCES	 += Devices/EX-SDI/en332s_main.c
SOURCES	 += Devices/EX-SDI/en332s_ucc.c
SOURCES	 += Devices/FPGA/lcmx03lf.c
SOURCES	 += Devices/FPGA/liamd6k.c
SOURCES	 += Devices/HDMI/ITE6615/ITE6615_CEC_DRV.c
SOURCES	 += Devices/HDMI/ITE6615/ITE6615_CEC_FETURE.c
SOURCES	 += Devices/HDMI/ITE6615/ITE6615_CEC_SYS.c
SOURCES	 += Devices/HDMI/ITE6615/ITE6615_DRV_TX.c
SOURCES	 += Devices/HDMI/ITE6615/ITE6615_EDID_PARSER.c
SOURCES	 += Devices/HDMI/ITE6615/ITE6615_EVB_Debug.c
SOURCES	 += Devices/HDMI/ITE6615/ITE6615_I2C_RDWR.c
SOURCES	 += Devices/HDMI/ITE6615/ITE6615_sha1.c
SOURCES	 += Devices/HDMI/ITE6615/ITE6615_SYS_FLOW.c
SOURCES	 += Devices/HDMI/IT66121/it66121.c
SOURCES	 += Devices/HDMI/IT66121/it66121_cec.c
SOURCES	 += Devices/HDMI/IT66121/it66121_csc.c
SOURCES	 += Devices/HDMI/IT66121/it66121_drv.c
SOURCES	 += Devices/HDMI/IT66121/it66121_hdcp.c
SOURCES	 += Devices/HDMI/IT66121/it66121_input.c
SOURCES	 += Devices/HDMI/IT66121/it66121_sys.c
SOURCES	 += Devices/HDMI/IT66121/sha1.c
SOURCES	 += Devices/HDMI/IT6802/it680x.c
SOURCES	 += Devices/HDMI/IT6802/it680x_cec.c
SOURCES	 += Devices/HDMI/IT6802/it680x_edid.c
SOURCES	 += Devices/HDMI/LT8618/lt8618ex.c
SOURCES	 += Devices/HDMI/LT8618/lt8618sx.c
SOURCES	 += Devices/HDMI/LT8619C/hdrx_edid.c
SOURCES	 += Devices/HDMI/LT8619C/lt8619c.c
SOURCES	 += Devices/HDMI/PS8409/ps8409.c
SOURCES	 += Devices/HDMI/SIL9136/AV_Config.c
SOURCES	 += Devices/HDMI/SIL9136/Globals.c
SOURCES	 += Devices/HDMI/SIL9136/sil9136.c
SOURCES	 += Devices/HDMI/SIL9136/TPI.c
SOURCES	 += Devices/HDMI/SIL9136/TPI_Access.c
SOURCES	 += Devices/HDMI/SIL9136/VideoModeTable.c
SOURCES	 += Devices/PLL/cdce913.c
SOURCES	 += Devices/TVI/tp2912.c
SOURCES	 += Drivers/init/Init_ODM.c
SOURCES	 += Drivers/misp100.c
SOURCES	 += Drivers/mispadc.c
SOURCES	 += Drivers/mispbayer.c
SOURCES	 += Drivers/mispbus.c
SOURCES	 += Drivers/mispcac.c
SOURCES	 += Drivers/mispclk.c
SOURCES	 += Drivers/mispcsc.c
SOURCES	 += Drivers/mispcur.c
SOURCES	 += Drivers/mispcolorcorrection.c
SOURCES	 += Drivers/mispdemosaic.c
SOURCES	 += Drivers/mispdis.c
SOURCES	 += Drivers/mispdpc.c
SOURCES	 += Drivers/mispfc.c
SOURCES	 += Drivers/mispfrmt.c
SOURCES	 += Drivers/mispgac.c
SOURCES	 += Drivers/misphost.c
SOURCES	 += Drivers/mispinput.c
SOURCES	 += Drivers/mispmdpm.c
SOURCES	 += Drivers/mispmemory_map.c
SOURCES	 += Drivers/mispnr.c
SOURCES	 += Drivers/misposd.c
SOURCES	 += Drivers/mispoutput.c
SOURCES	 += Drivers/misprotation.c
SOURCES	 += Drivers/mispsensor_top.c
SOURCES	 += Drivers/misptone.c
SOURCES	 += Drivers/mispcsp.c
SOURCES	 += Drivers/mispwdr.c
SOURCES	 += Graphic/item.c
SOURCES	 += Graphic/menu.c
SOURCES	 += Graphic/osd.c
SOURCES	 += LENS/iris_if.c
SOURCES	 += LENS/lens_if.c
SOURCES	 += Lucida/lib_src/ae32000_store_func.c
SOURCES	 += Lucida/lib_src/cpu_cache_util.S
SOURCES	 += Lucida/lib_src/cpu_clockctrl.c
SOURCES	 += Lucida/lib_src/cpu_debugprintf.c
SOURCES	 += Lucida/lib_src/cpu_interrupt.c
SOURCES	 += Lucida/lib_src/cpu_sfctrl.c
SOURCES	 += Lucida/lib_src/cpu_spi.c
SOURCES	 += Lucida/lib_src/cpu_timer.c
SOURCES	 += Lucida/lib_src/cpu_twi.c
SOURCES	 += Lucida/lib_src/cpu_uart.c
SOURCES	 += Lucida/lib_src/cpu_util.c
SOURCES	 += Lucida/startup/MacroInit.c
SOURCES	 += Lucida/startup/startup.s
SOURCES	 += Protocol/pelco_app.c
SOURCES	 += Protocol/pelco_drv.c
SOURCES	 += Protocol/spim_app.c
SOURCES	 += Protocol/spim_drv.c
SOURCES	 += Protocol/spis_app.c
SOURCES	 += Protocol/spis_drv.c
SOURCES	 += Protocol/usb_app.c
SOURCES	 += Protocol/visca_app.c
SOURCES	 += Protocol/visca_drv.c
SOURCES	 += Video/ae.c
SOURCES	 += Video/ae_agc.c
SOURCES	 += Video/ae_aux.c
SOURCES	 += Video/ae_blc.c
SOURCES	 += Video/ae_core.c
SOURCES	 += Video/ae_hall.c
SOURCES	 += Video/ae_iris.c
SOURCES	 += Video/ae_pwm.c
SOURCES	 += Video/ae_sht.c
SOURCES	 += Video/awb.c
SOURCES	 += Video/awb_aux.c
SOURCES	 += Video/awb_color.c
SOURCES	 += Video/awb_core.c
SOURCES	 += Video/demo.c
SOURCES	 += Video/misc.c
SOURCES	 += Video/video.c

OBJECTS	 += ${OBJDIR}app_3a.o
OBJECTS	 += ${OBJDIR}app_4k60.o
OBJECTS	 += ${OBJDIR}app_initial.o
OBJECTS	 += ${OBJDIR}app_pano.o
OBJECTS	 += ${OBJDIR}app_cascade_cam.o
OBJECTS	 += ${OBJDIR}app_picture_style.o
OBJECTS	 += ${OBJDIR}app_lowlight_control.o
OBJECTS	 += ${OBJDIR}app_sync_lock.o
OBJECTS	 += ${OBJDIR}main.o
OBJECTS	 += ${OBJDIR}ar0134.o
OBJECTS	 += ${OBJDIR}ar0331.o
OBJECTS	 += ${OBJDIR}cmos_if.o
OBJECTS	 += ${OBJDIR}imx076.o
OBJECTS	 += ${OBJDIR}imx124.o
OBJECTS	 += ${OBJDIR}imx252.o
OBJECTS	 += ${OBJDIR}imx265.o
OBJECTS	 += ${OBJDIR}imx253.o
OBJECTS	 += ${OBJDIR}imx273.o
OBJECTS	 += ${OBJDIR}imx136.o
OBJECTS	 += ${OBJDIR}imx174.o
OBJECTS	 += ${OBJDIR}imx178.o
OBJECTS	 += ${OBJDIR}imx185.o
OBJECTS	 += ${OBJDIR}imx222.o
OBJECTS	 += ${OBJDIR}imx226.o
OBJECTS	 += ${OBJDIR}imx274.o
OBJECTS	 += ${OBJDIR}imx238.o
OBJECTS	 += ${OBJDIR}imx290.o
OBJECTS	 += ${OBJDIR}imx385.o
OBJECTS	 += ${OBJDIR}imx334.o
OBJECTS	 += ${OBJDIR}imx326.o
OBJECTS	 += ${OBJDIR}mn34041.o
OBJECTS	 += ${OBJDIR}mn34220.o
OBJECTS	 += ${OBJDIR}mn34420.o
OBJECTS	 += ${OBJDIR}mt9m131.o
OBJECTS	 += ${OBJDIR}mt9p031.o
OBJECTS	 += ${OBJDIR}ov2710.o
OBJECTS	 += ${OBJDIR}po3100k.o
OBJECTS	 += ${OBJDIR}ps1210k.o
OBJECTS	 += ${OBJDIR}ps1400k.o
OBJECTS	 += ${OBJDIR}cmdproc.o
OBJECTS	 += ${OBJDIR}cmds.o
OBJECTS	 += ${OBJDIR}delay.o
OBJECTS	 += ${OBJDIR}i2c.o
OBJECTS	 += ${OBJDIR}init.o
OBJECTS	 += ${OBJDIR}ir.o
OBJECTS	 += ${OBJDIR}isr.o
OBJECTS	 += ${OBJDIR}key.o
OBJECTS	 += ${OBJDIR}msg.o
OBJECTS	 += ${OBJDIR}serial.o
OBJECTS	 += ${OBJDIR}spi.o
OBJECTS	 += ${OBJDIR}en332s_main.o
OBJECTS	 += ${OBJDIR}en332s_ucc.o
OBJECTS	 += ${OBJDIR}lcmx03lf.o
OBJECTS	 += ${OBJDIR}liamd6k.o
OBJECTS	 += ${OBJDIR}ITE6615_CEC_DRV.o
OBJECTS	 += ${OBJDIR}ITE6615_CEC_FETURE.o
OBJECTS	 += ${OBJDIR}ITE6615_CEC_SYS.o
OBJECTS	 += ${OBJDIR}ITE6615_DRV_TX.o
OBJECTS	 += ${OBJDIR}ITE6615_EDID_PARSER.o
OBJECTS	 += ${OBJDIR}ITE6615_EVB_Debug.o
OBJECTS	 += ${OBJDIR}ITE6615_I2C_RDWR.o
OBJECTS	 += ${OBJDIR}ITE6615_sha1.o
OBJECTS	 += ${OBJDIR}ITE6615_SYS_FLOW.o
OBJECTS	 += ${OBJDIR}it66121.o
OBJECTS	 += ${OBJDIR}it66121_cec.o
OBJECTS	 += ${OBJDIR}it66121_csc.o
OBJECTS	 += ${OBJDIR}it66121_drv.o
OBJECTS	 += ${OBJDIR}it66121_hdcp.o
OBJECTS	 += ${OBJDIR}it66121_input.o
OBJECTS	 += ${OBJDIR}it66121_sys.o
OBJECTS	 += ${OBJDIR}sha1.o
OBJECTS	 += ${OBJDIR}it680x.o
OBJECTS	 += ${OBJDIR}it680x_cec.o
OBJECTS	 += ${OBJDIR}it680x_edid.o
OBJECTS	 += ${OBJDIR}lt8618ex.o
OBJECTS	 += ${OBJDIR}lt8618sx.o
OBJECTS	 += ${OBJDIR}hdrx_edid.o
OBJECTS	 += ${OBJDIR}lt8619c.o
OBJECTS	 += ${OBJDIR}ps8409.o
OBJECTS	 += ${OBJDIR}AV_Config.o
OBJECTS	 += ${OBJDIR}Globals.o
OBJECTS	 += ${OBJDIR}sil9136.o
OBJECTS	 += ${OBJDIR}TPI.o
OBJECTS	 += ${OBJDIR}TPI_Access.o
OBJECTS	 += ${OBJDIR}VideoModeTable.o
OBJECTS	 += ${OBJDIR}cdce913.o
OBJECTS	 += ${OBJDIR}tp2912.o
OBJECTS	 += ${OBJDIR}Init_ODM.o
OBJECTS	 += ${OBJDIR}misp100.o
OBJECTS	 += ${OBJDIR}mispadc.o
OBJECTS	 += ${OBJDIR}mispbayer.o
OBJECTS	 += ${OBJDIR}mispbus.o
OBJECTS	 += ${OBJDIR}mispcac.o
OBJECTS	 += ${OBJDIR}mispclk.o
OBJECTS	 += ${OBJDIR}mispcsc.o
OBJECTS	 += ${OBJDIR}mispcur.o
OBJECTS	 += ${OBJDIR}mispcolorcorrection.o
OBJECTS	 += ${OBJDIR}mispdemosaic.o
OBJECTS	 += ${OBJDIR}mispdis.o
OBJECTS	 += ${OBJDIR}mispdpc.o
OBJECTS	 += ${OBJDIR}mispfc.o
OBJECTS	 += ${OBJDIR}mispfrmt.o
OBJECTS	 += ${OBJDIR}mispgac.o
OBJECTS	 += ${OBJDIR}misphost.o
OBJECTS	 += ${OBJDIR}mispinput.o
OBJECTS	 += ${OBJDIR}mispmdpm.o
OBJECTS	 += ${OBJDIR}mispmemory_map.o
OBJECTS	 += ${OBJDIR}mispnr.o
OBJECTS	 += ${OBJDIR}misposd.o
OBJECTS	 += ${OBJDIR}mispoutput.o
OBJECTS	 += ${OBJDIR}misprotation.o
OBJECTS	 += ${OBJDIR}mispsensor_top.o
OBJECTS	 += ${OBJDIR}misptone.o
OBJECTS	 += ${OBJDIR}mispcsp.o
OBJECTS	 += ${OBJDIR}mispwdr.o
OBJECTS	 += ${OBJDIR}item.o
OBJECTS	 += ${OBJDIR}menu.o
OBJECTS	 += ${OBJDIR}osd.o
OBJECTS	 += ${OBJDIR}iris_if.o
OBJECTS	 += ${OBJDIR}lens_if.o
OBJECTS	 += ${OBJDIR}ae32000_store_func.o
OBJECTS	 += ${OBJDIR}cpu_cache_util.o
OBJECTS	 += ${OBJDIR}cpu_clockctrl.o
OBJECTS	 += ${OBJDIR}cpu_debugprintf.o
OBJECTS	 += ${OBJDIR}cpu_interrupt.o
OBJECTS	 += ${OBJDIR}cpu_sfctrl.o
OBJECTS	 += ${OBJDIR}cpu_spi.o
OBJECTS	 += ${OBJDIR}cpu_timer.o
OBJECTS	 += ${OBJDIR}cpu_twi.o
OBJECTS	 += ${OBJDIR}cpu_uart.o
OBJECTS	 += ${OBJDIR}cpu_util.o
OBJECTS	 += ${OBJDIR}MacroInit.o
OBJECTS	 += ${OBJDIR}startup.o
OBJECTS	 += ${OBJDIR}pelco_app.o
OBJECTS	 += ${OBJDIR}pelco_drv.o
OBJECTS	 += ${OBJDIR}spim_app.o
OBJECTS	 += ${OBJDIR}spim_drv.o
OBJECTS	 += ${OBJDIR}spis_app.o
OBJECTS	 += ${OBJDIR}spis_drv.o
OBJECTS	 += ${OBJDIR}usb_app.o
OBJECTS	 += ${OBJDIR}visca_app.o
OBJECTS	 += ${OBJDIR}visca_drv.o
OBJECTS	 += ${OBJDIR}ae.o
OBJECTS	 += ${OBJDIR}ae_agc.o
OBJECTS	 += ${OBJDIR}ae_aux.o
OBJECTS	 += ${OBJDIR}ae_blc.o
OBJECTS	 += ${OBJDIR}ae_core.o
OBJECTS	 += ${OBJDIR}ae_hall.o
OBJECTS	 += ${OBJDIR}ae_iris.o
OBJECTS	 += ${OBJDIR}ae_pwm.o
OBJECTS	 += ${OBJDIR}ae_sht.o
OBJECTS	 += ${OBJDIR}awb.o
OBJECTS	 += ${OBJDIR}awb_aux.o
OBJECTS	 += ${OBJDIR}awb_color.o
OBJECTS	 += ${OBJDIR}awb_core.o
OBJECTS	 += ${OBJDIR}demo.o
OBJECTS	 += ${OBJDIR}misc.o
OBJECTS	 += ${OBJDIR}video.o

DEPS	 += ${OBJDIR}app_3a.d
DEPS	 += ${OBJDIR}app_4k60.d
DEPS	 += ${OBJDIR}app_initial.d
DEPS	 += ${OBJDIR}app_pano.d
DEPS	 += ${OBJDIR}app_cascade_cam.d
DEPS	 += ${OBJDIR}app_picture_style.d
DEPS	 += ${OBJDIR}app_lowlight_control.d
DEPS	 += ${OBJDIR}app_sync_lock.d
DEPS	 += ${OBJDIR}main.d
DEPS	 += ${OBJDIR}ar0134.d
DEPS	 += ${OBJDIR}ar0331.d
DEPS	 += ${OBJDIR}cmos_if.d
DEPS	 += ${OBJDIR}imx076.d
DEPS	 += ${OBJDIR}imx124.d
DEPS	 += ${OBJDIR}imx252.d
DEPS	 += ${OBJDIR}imx265.d
DEPS	 += ${OBJDIR}imx253.d
DEPS	 += ${OBJDIR}imx273.d
DEPS	 += ${OBJDIR}imx136.d
DEPS	 += ${OBJDIR}imx174.d
DEPS	 += ${OBJDIR}imx178.d
DEPS	 += ${OBJDIR}imx185.d
DEPS	 += ${OBJDIR}imx222.d
DEPS	 += ${OBJDIR}imx226.d
DEPS	 += ${OBJDIR}imx274.d
DEPS	 += ${OBJDIR}imx238.d
DEPS	 += ${OBJDIR}imx290.d
DEPS	 += ${OBJDIR}imx385.d
DEPS	 += ${OBJDIR}imx334.d
DEPS	 += ${OBJDIR}imx326.d
DEPS	 += ${OBJDIR}mn34041.d
DEPS	 += ${OBJDIR}mn34220.d
DEPS	 += ${OBJDIR}mn34420.d
DEPS	 += ${OBJDIR}mt9m131.d
DEPS	 += ${OBJDIR}mt9p031.d
DEPS	 += ${OBJDIR}ov2710.d
DEPS	 += ${OBJDIR}po3100k.d
DEPS	 += ${OBJDIR}ps1210k.d
DEPS	 += ${OBJDIR}ps1400k.d
DEPS	 += ${OBJDIR}cmdproc.d
DEPS	 += ${OBJDIR}cmds.d
DEPS	 += ${OBJDIR}delay.d
DEPS	 += ${OBJDIR}i2c.d
DEPS	 += ${OBJDIR}init.d
DEPS	 += ${OBJDIR}ir.d
DEPS	 += ${OBJDIR}isr.d
DEPS	 += ${OBJDIR}key.d
DEPS	 += ${OBJDIR}msg.d
DEPS	 += ${OBJDIR}serial.d
DEPS	 += ${OBJDIR}spi.d
DEPS	 += ${OBJDIR}en332s_main.d
DEPS	 += ${OBJDIR}en332s_ucc.d
DEPS	 += ${OBJDIR}lcmx03lf.d
DEPS	 += ${OBJDIR}liamd6k.d
DEPS	 += ${OBJDIR}ITE6615_CEC_DRV.d
DEPS	 += ${OBJDIR}ITE6615_CEC_FETURE.d
DEPS	 += ${OBJDIR}ITE6615_CEC_SYS.d
DEPS	 += ${OBJDIR}ITE6615_DRV_TX.d
DEPS	 += ${OBJDIR}ITE6615_EDID_PARSER.d
DEPS	 += ${OBJDIR}ITE6615_EVB_Debug.d
DEPS	 += ${OBJDIR}ITE6615_I2C_RDWR.d
DEPS	 += ${OBJDIR}ITE6615_sha1.d
DEPS	 += ${OBJDIR}ITE6615_SYS_FLOW.d
DEPS	 += ${OBJDIR}it66121.d
DEPS	 += ${OBJDIR}it66121_cec.d
DEPS	 += ${OBJDIR}it66121_csc.d
DEPS	 += ${OBJDIR}it66121_drv.d
DEPS	 += ${OBJDIR}it66121_hdcp.d
DEPS	 += ${OBJDIR}it66121_input.d
DEPS	 += ${OBJDIR}it66121_sys.d
DEPS	 += ${OBJDIR}sha1.d
DEPS	 += ${OBJDIR}it680x.d
DEPS	 += ${OBJDIR}it680x_cec.d
DEPS	 += ${OBJDIR}it680x_edid.d
DEPS	 += ${OBJDIR}lt8618ex.d
DEPS	 += ${OBJDIR}lt8618sx.d
DEPS	 += ${OBJDIR}hdrx_edid.d
DEPS	 += ${OBJDIR}lt8619c.d
DEPS	 += ${OBJDIR}ps8409.d
DEPS	 += ${OBJDIR}AV_Config.d
DEPS	 += ${OBJDIR}Globals.d
DEPS	 += ${OBJDIR}sil9136.d
DEPS	 += ${OBJDIR}TPI.d
DEPS	 += ${OBJDIR}TPI_Access.d
DEPS	 += ${OBJDIR}VideoModeTable.d
DEPS	 += ${OBJDIR}cdce913.d
DEPS	 += ${OBJDIR}tp2912.d
DEPS	 += ${OBJDIR}Init_ODM.d
DEPS	 += ${OBJDIR}misp100.d
DEPS	 += ${OBJDIR}mispadc.d
DEPS	 += ${OBJDIR}mispbayer.d
DEPS	 += ${OBJDIR}mispbus.d
DEPS	 += ${OBJDIR}mispcac.d
DEPS	 += ${OBJDIR}mispclk.d
DEPS	 += ${OBJDIR}mispcsc.d
DEPS	 += ${OBJDIR}mispcur.d
DEPS	 += ${OBJDIR}mispcolorcorrection.d
DEPS	 += ${OBJDIR}mispdemosaic.d
DEPS	 += ${OBJDIR}mispdis.d
DEPS	 += ${OBJDIR}mispdpc.d
DEPS	 += ${OBJDIR}mispfc.d
DEPS	 += ${OBJDIR}mispfrmt.d
DEPS	 += ${OBJDIR}mispgac.d
DEPS	 += ${OBJDIR}misphost.d
DEPS	 += ${OBJDIR}mispinput.d
DEPS	 += ${OBJDIR}mispmdpm.d
DEPS	 += ${OBJDIR}mispmemory_map.d
DEPS	 += ${OBJDIR}mispnr.d
DEPS	 += ${OBJDIR}misposd.d
DEPS	 += ${OBJDIR}mispoutput.d
DEPS	 += ${OBJDIR}misprotation.d
DEPS	 += ${OBJDIR}mispsensor_top.d
DEPS	 += ${OBJDIR}misptone.d
DEPS	 += ${OBJDIR}mispcsp.d
DEPS	 += ${OBJDIR}mispwdr.d
DEPS	 += ${OBJDIR}item.d
DEPS	 += ${OBJDIR}menu.d
DEPS	 += ${OBJDIR}osd.d
DEPS	 += ${OBJDIR}iris_if.d
DEPS	 += ${OBJDIR}lens_if.d
DEPS	 += ${OBJDIR}ae32000_store_func.d
DEPS	 += ${OBJDIR}cpu_cache_util.d
DEPS	 += ${OBJDIR}cpu_clockctrl.d
DEPS	 += ${OBJDIR}cpu_debugprintf.d
DEPS	 += ${OBJDIR}cpu_interrupt.d
DEPS	 += ${OBJDIR}cpu_sfctrl.d
DEPS	 += ${OBJDIR}cpu_spi.d
DEPS	 += ${OBJDIR}cpu_timer.d
DEPS	 += ${OBJDIR}cpu_twi.d
DEPS	 += ${OBJDIR}cpu_uart.d
DEPS	 += ${OBJDIR}cpu_util.d
DEPS	 += ${OBJDIR}MacroInit.d
DEPS	 += ${OBJDIR}startup.d
DEPS	 += ${OBJDIR}pelco_app.d
DEPS	 += ${OBJDIR}pelco_drv.d
DEPS	 += ${OBJDIR}spim_app.d
DEPS	 += ${OBJDIR}spim_drv.d
DEPS	 += ${OBJDIR}spis_app.d
DEPS	 += ${OBJDIR}spis_drv.d
DEPS	 += ${OBJDIR}usb_app.d
DEPS	 += ${OBJDIR}visca_app.d
DEPS	 += ${OBJDIR}visca_drv.d
DEPS	 += ${OBJDIR}ae.d
DEPS	 += ${OBJDIR}ae_agc.d
DEPS	 += ${OBJDIR}ae_aux.d
DEPS	 += ${OBJDIR}ae_blc.d
DEPS	 += ${OBJDIR}ae_core.d
DEPS	 += ${OBJDIR}ae_hall.d
DEPS	 += ${OBJDIR}ae_iris.d
DEPS	 += ${OBJDIR}ae_pwm.d
DEPS	 += ${OBJDIR}ae_sht.d
DEPS	 += ${OBJDIR}awb.d
DEPS	 += ${OBJDIR}awb_aux.d
DEPS	 += ${OBJDIR}awb_color.d
DEPS	 += ${OBJDIR}awb_core.d
DEPS	 += ${OBJDIR}demo.d
DEPS	 += ${OBJDIR}misc.d
DEPS	 += ${OBJDIR}video.d



#====== TAGET Define =====
TARGET	=	$(OUTPUTDIR)MISP100-EDK_ADC.elf

BINARY	=	$(TARGET).bin

HEX	=	$(TARGET).hex

DISASSEMBLE	=	$(TARGET).dis

ALL	:	$(TARGET) $(BINARY) 

all	:	$(TARGET) $(BINARY) 

binary	:	$(BINARY)

bin	:	$(BINARY)

hex	:	$(HEX)

disassemble	:	$(DISASSEMBLE)

dis	:	$(DISASSEMBLE)

clean	:
	@$(ECHO) 'Deleting intermediate and output files... '
	rm -f $(OBJECTS) $(TARGET) $(DISASSEMBLE) $(BINARY) $(DEPS)
	@$(ECHO) ' '

cleanall	:
	@$(ECHO) 'Deleting intermediate and output files... '
	rm -f $(OBJECTS) $(TARGET) $(DISASSEMBLE) $(BINARY) $(DEPS)
	@$(ECHO) ' '

cleanobj	:
	@$(ECHO) 'Deleting intermediate files... '
	rm -f $(OBJECTS) 
	@$(ECHO) ' '

cleanbin	:
	rm -f $(BINARY)
	@$(ECHO) ' '

cleandis	:
	rm -f $(DISASSEMBLE)
	@$(ECHO) ' '

ifeq ($(FULLMSG),no)
ECHOMARK = @
else
ECHOMARK = 
endif

-include ${OBJDIR}app_3a.d
-include ${OBJDIR}app_4k60.d
-include ${OBJDIR}app_initial.d
-include ${OBJDIR}app_pano.d
-include ${OBJDIR}app_cascade_cam.d
-include ${OBJDIR}app_picture_style.d
-include ${OBJDIR}app_lowlight_control.d
-include ${OBJDIR}app_sync_lock.d
-include ${OBJDIR}main.d
-include ${OBJDIR}ar0134.d
-include ${OBJDIR}ar0331.d
-include ${OBJDIR}cmos_if.d
-include ${OBJDIR}imx076.d
-include ${OBJDIR}imx124.d
-include ${OBJDIR}imx252.d
-include ${OBJDIR}imx265.d
-include ${OBJDIR}imx253.d
-include ${OBJDIR}imx273.d
-include ${OBJDIR}imx136.d
-include ${OBJDIR}imx174.d
-include ${OBJDIR}imx178.d
-include ${OBJDIR}imx185.d
-include ${OBJDIR}imx222.d
-include ${OBJDIR}imx226.d
-include ${OBJDIR}imx274.d
-include ${OBJDIR}imx238.d
-include ${OBJDIR}imx290.d
-include ${OBJDIR}imx385.d
-include ${OBJDIR}imx334.d
-include ${OBJDIR}imx326.d
-include ${OBJDIR}mn34041.d
-include ${OBJDIR}mn34220.d
-include ${OBJDIR}mn34420.d
-include ${OBJDIR}mt9m131.d
-include ${OBJDIR}mt9p031.d
-include ${OBJDIR}ov2710.d
-include ${OBJDIR}po3100k.d
-include ${OBJDIR}ps1210k.d
-include ${OBJDIR}ps1400k.d
-include ${OBJDIR}cmdproc.d
-include ${OBJDIR}cmds.d
-include ${OBJDIR}delay.d
-include ${OBJDIR}i2c.d
-include ${OBJDIR}init.d
-include ${OBJDIR}ir.d
-include ${OBJDIR}isr.d
-include ${OBJDIR}key.d
-include ${OBJDIR}msg.d
-include ${OBJDIR}serial.d
-include ${OBJDIR}spi.d
-include ${OBJDIR}en332s_main.d
-include ${OBJDIR}en332s_ucc.d
-include ${OBJDIR}lcmx03lf.d
-include ${OBJDIR}liamd6k.d
-include ${OBJDIR}ITE6615_CEC_DRV.d
-include ${OBJDIR}ITE6615_CEC_FETURE.d
-include ${OBJDIR}ITE6615_CEC_SYS.d
-include ${OBJDIR}ITE6615_DRV_TX.d
-include ${OBJDIR}ITE6615_EDID_PARSER.d
-include ${OBJDIR}ITE6615_EVB_Debug.d
-include ${OBJDIR}ITE6615_I2C_RDWR.d
-include ${OBJDIR}ITE6615_sha1.d
-include ${OBJDIR}ITE6615_SYS_FLOW.d
-include ${OBJDIR}it66121.d
-include ${OBJDIR}it66121_cec.d
-include ${OBJDIR}it66121_csc.d
-include ${OBJDIR}it66121_drv.d
-include ${OBJDIR}it66121_hdcp.d
-include ${OBJDIR}it66121_input.d
-include ${OBJDIR}it66121_sys.d
-include ${OBJDIR}sha1.d
-include ${OBJDIR}it680x.d
-include ${OBJDIR}it680x_cec.d
-include ${OBJDIR}it680x_edid.d
-include ${OBJDIR}lt8618ex.d
-include ${OBJDIR}lt8618sx.d
-include ${OBJDIR}hdrx_edid.d
-include ${OBJDIR}lt8619c.d
-include ${OBJDIR}ps8409.d
-include ${OBJDIR}AV_Config.d
-include ${OBJDIR}Globals.d
-include ${OBJDIR}sil9136.d
-include ${OBJDIR}TPI.d
-include ${OBJDIR}TPI_Access.d
-include ${OBJDIR}VideoModeTable.d
-include ${OBJDIR}cdce913.d
-include ${OBJDIR}tp2912.d
-include ${OBJDIR}Init_ODM.d
-include ${OBJDIR}misp100.d
-include ${OBJDIR}mispadc.d
-include ${OBJDIR}mispbayer.d
-include ${OBJDIR}mispbus.d
-include ${OBJDIR}mispcac.d
-include ${OBJDIR}mispclk.d
-include ${OBJDIR}mispcsc.d
-include ${OBJDIR}mispcur.d
-include ${OBJDIR}mispcolorcorrection.d
-include ${OBJDIR}mispdemosaic.d
-include ${OBJDIR}mispdis.d
-include ${OBJDIR}mispdpc.d
-include ${OBJDIR}mispfc.d
-include ${OBJDIR}mispfrmt.d
-include ${OBJDIR}mispgac.d
-include ${OBJDIR}misphost.d
-include ${OBJDIR}mispinput.d
-include ${OBJDIR}mispmdpm.d
-include ${OBJDIR}mispmemory_map.d
-include ${OBJDIR}mispnr.d
-include ${OBJDIR}misposd.d
-include ${OBJDIR}mispoutput.d
-include ${OBJDIR}misprotation.d
-include ${OBJDIR}mispsensor_top.d
-include ${OBJDIR}misptone.d
-include ${OBJDIR}mispcsp.d
-include ${OBJDIR}mispwdr.d
-include ${OBJDIR}item.d
-include ${OBJDIR}menu.d
-include ${OBJDIR}osd.d
-include ${OBJDIR}iris_if.d
-include ${OBJDIR}lens_if.d
-include ${OBJDIR}ae32000_store_func.d
-include ${OBJDIR}cpu_cache_util.d
-include ${OBJDIR}cpu_clockctrl.d
-include ${OBJDIR}cpu_debugprintf.d
-include ${OBJDIR}cpu_interrupt.d
-include ${OBJDIR}cpu_sfctrl.d
-include ${OBJDIR}cpu_spi.d
-include ${OBJDIR}cpu_timer.d
-include ${OBJDIR}cpu_twi.d
-include ${OBJDIR}cpu_uart.d
-include ${OBJDIR}cpu_util.d
-include ${OBJDIR}MacroInit.d
-include ${OBJDIR}startup.d
-include ${OBJDIR}pelco_app.d
-include ${OBJDIR}pelco_drv.d
-include ${OBJDIR}spim_app.d
-include ${OBJDIR}spim_drv.d
-include ${OBJDIR}spis_app.d
-include ${OBJDIR}spis_drv.d
-include ${OBJDIR}usb_app.d
-include ${OBJDIR}visca_app.d
-include ${OBJDIR}visca_drv.d
-include ${OBJDIR}ae.d
-include ${OBJDIR}ae_agc.d
-include ${OBJDIR}ae_aux.d
-include ${OBJDIR}ae_blc.d
-include ${OBJDIR}ae_core.d
-include ${OBJDIR}ae_hall.d
-include ${OBJDIR}ae_iris.d
-include ${OBJDIR}ae_pwm.d
-include ${OBJDIR}ae_sht.d
-include ${OBJDIR}awb.d
-include ${OBJDIR}awb_aux.d
-include ${OBJDIR}awb_color.d
-include ${OBJDIR}awb_core.d
-include ${OBJDIR}demo.d
-include ${OBJDIR}misc.d
-include ${OBJDIR}video.d

#============= TARGET ====================
${TARGET} : Makefile.mk ${OBJECTS} ${LIBS} Lucida/startup/macroimg_ispm64k_dspm64k.ld
	@$(ECHO) 'Linking...'
	$(ECHOMARK)$(CC) -o $(TARGET) $(OBJECTS) $(LIBDIR) -Xlinker --start-group $(LIBS) -Xlinker --end-group $(LDFLAGS) -Xlinker -T"Lucida/startup/macroimg_ispm64k_dspm64k.ld"
	@$(ECHO) 'Finished building : $@ '
	@$(ECHO) ' '

$(BINARY): $(TARGET)
	@$(ECHO) 'Generating binary file...'
	$(ECHOMARK)$(OBJCOPY) -O binary $(TARGET) $@
	@$(ECHO) 'Finished building : $@ '
	@$(ECHO) ' '
	@$(ECHO) 'Program section information '
	$(ECHOMARK)size $(TARGET)
	@$(ECHO) ' '

$(DISASSEMBLE) : $(TARGET)
	@$(ECHO) 'Generating disassemble file...'
	$(ECHOMARK)$(OBJDUMP) $(DISFLAGS) $(TARGET) > $@ 
	@$(ECHO) 'Finished building : $@ '
	@$(ECHO) ' '

${OBJDIR}app_3a.o : App/app_3a.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}app_4k60.o : App/app_4k60.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}app_initial.o : App/app_initial.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}app_pano.o : App/app_pano.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}app_cascade_cam.o : App/app_cascade_cam.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}app_picture_style.o : App/app_picture_style.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}app_lowlight_control.o : App/app_lowlight_control.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}app_sync_lock.o : App/app_sync_lock.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}main.o : App/main.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}ar0134.o : CMOS/ar0134.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}ar0331.o : CMOS/ar0331.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}cmos_if.o : CMOS/cmos_if.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}imx076.o : CMOS/imx076.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}imx124.o : CMOS/imx124.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}imx252.o : CMOS/imx252.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}imx265.o : CMOS/imx265.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}imx253.o : CMOS/imx253.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}imx273.o : CMOS/imx273.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}imx136.o : CMOS/imx136.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}imx174.o : CMOS/imx174.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}imx178.o : CMOS/imx178.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}imx185.o : CMOS/imx185.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}imx222.o : CMOS/imx222.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}imx226.o : CMOS/imx226.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}imx274.o : CMOS/imx274.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}imx238.o : CMOS/imx238.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}imx290.o : CMOS/imx290.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}imx385.o : CMOS/imx385.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}imx334.o : CMOS/imx334.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}imx326.o : CMOS/imx326.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}mn34041.o : CMOS/mn34041.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}mn34220.o : CMOS/mn34220.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}mn34420.o : CMOS/mn34420.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}mt9m131.o : CMOS/mt9m131.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}mt9p031.o : CMOS/mt9p031.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}ov2710.o : CMOS/ov2710.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}po3100k.o : CMOS/po3100k.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}ps1210k.o : CMOS/ps1210k.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}ps1400k.o : CMOS/ps1400k.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}cmdproc.o : Common/cmdproc.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}cmds.o : Common/cmds.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}delay.o : Common/delay.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}i2c.o : Common/i2c.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}init.o : Common/init.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}ir.o : Common/ir.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}isr.o : Common/isr.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}key.o : Common/key.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}msg.o : Common/msg.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}serial.o : Common/serial.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}spi.o : Common/spi.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}en332s_main.o : Devices/EX-SDI/en332s_main.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}en332s_ucc.o : Devices/EX-SDI/en332s_ucc.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}lcmx03lf.o : Devices/FPGA/lcmx03lf.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}liamd6k.o : Devices/FPGA/liamd6k.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}ITE6615_CEC_DRV.o : Devices/HDMI/ITE6615/ITE6615_CEC_DRV.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}ITE6615_CEC_FETURE.o : Devices/HDMI/ITE6615/ITE6615_CEC_FETURE.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}ITE6615_CEC_SYS.o : Devices/HDMI/ITE6615/ITE6615_CEC_SYS.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}ITE6615_DRV_TX.o : Devices/HDMI/ITE6615/ITE6615_DRV_TX.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}ITE6615_EDID_PARSER.o : Devices/HDMI/ITE6615/ITE6615_EDID_PARSER.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}ITE6615_EVB_Debug.o : Devices/HDMI/ITE6615/ITE6615_EVB_Debug.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}ITE6615_I2C_RDWR.o : Devices/HDMI/ITE6615/ITE6615_I2C_RDWR.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}ITE6615_sha1.o : Devices/HDMI/ITE6615/ITE6615_sha1.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}ITE6615_SYS_FLOW.o : Devices/HDMI/ITE6615/ITE6615_SYS_FLOW.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}it66121.o : Devices/HDMI/IT66121/it66121.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}it66121_cec.o : Devices/HDMI/IT66121/it66121_cec.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}it66121_csc.o : Devices/HDMI/IT66121/it66121_csc.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}it66121_drv.o : Devices/HDMI/IT66121/it66121_drv.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}it66121_hdcp.o : Devices/HDMI/IT66121/it66121_hdcp.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}it66121_input.o : Devices/HDMI/IT66121/it66121_input.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}it66121_sys.o : Devices/HDMI/IT66121/it66121_sys.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}sha1.o : Devices/HDMI/IT66121/sha1.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}it680x.o : Devices/HDMI/IT6802/it680x.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}it680x_cec.o : Devices/HDMI/IT6802/it680x_cec.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}it680x_edid.o : Devices/HDMI/IT6802/it680x_edid.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}lt8618ex.o : Devices/HDMI/LT8618/lt8618ex.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}lt8618sx.o : Devices/HDMI/LT8618/lt8618sx.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}hdrx_edid.o : Devices/HDMI/LT8619C/hdrx_edid.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}lt8619c.o : Devices/HDMI/LT8619C/lt8619c.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}ps8409.o : Devices/HDMI/PS8409/ps8409.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}AV_Config.o : Devices/HDMI/SIL9136/AV_Config.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}Globals.o : Devices/HDMI/SIL9136/Globals.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}sil9136.o : Devices/HDMI/SIL9136/sil9136.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}TPI.o : Devices/HDMI/SIL9136/TPI.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}TPI_Access.o : Devices/HDMI/SIL9136/TPI_Access.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}VideoModeTable.o : Devices/HDMI/SIL9136/VideoModeTable.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}cdce913.o : Devices/PLL/cdce913.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}tp2912.o : Devices/TVI/tp2912.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}Init_ODM.o : Drivers/init/Init_ODM.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}misp100.o : Drivers/misp100.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}mispadc.o : Drivers/mispadc.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}mispbayer.o : Drivers/mispbayer.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}mispbus.o : Drivers/mispbus.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}mispcac.o : Drivers/mispcac.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}mispclk.o : Drivers/mispclk.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}mispcsc.o : Drivers/mispcsc.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}mispcur.o : Drivers/mispcur.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}mispcolorcorrection.o : Drivers/mispcolorcorrection.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}mispdemosaic.o : Drivers/mispdemosaic.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}mispdis.o : Drivers/mispdis.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}mispdpc.o : Drivers/mispdpc.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}mispfc.o : Drivers/mispfc.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}mispfrmt.o : Drivers/mispfrmt.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}mispgac.o : Drivers/mispgac.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}misphost.o : Drivers/misphost.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}mispinput.o : Drivers/mispinput.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}mispmdpm.o : Drivers/mispmdpm.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}mispmemory_map.o : Drivers/mispmemory_map.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}mispnr.o : Drivers/mispnr.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}misposd.o : Drivers/misposd.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}mispoutput.o : Drivers/mispoutput.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}misprotation.o : Drivers/misprotation.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}mispsensor_top.o : Drivers/mispsensor_top.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}misptone.o : Drivers/misptone.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}mispcsp.o : Drivers/mispcsp.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}mispwdr.o : Drivers/mispwdr.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}item.o : Graphic/item.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}menu.o : Graphic/menu.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}osd.o : Graphic/osd.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}iris_if.o : LENS/iris_if.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}lens_if.o : LENS/lens_if.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}ae32000_store_func.o : Lucida/lib_src/ae32000_store_func.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}cpu_cache_util.o : Lucida/lib_src/cpu_cache_util.S
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) -Wa,$(ASFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}cpu_clockctrl.o : Lucida/lib_src/cpu_clockctrl.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}cpu_debugprintf.o : Lucida/lib_src/cpu_debugprintf.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}cpu_interrupt.o : Lucida/lib_src/cpu_interrupt.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}cpu_sfctrl.o : Lucida/lib_src/cpu_sfctrl.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}cpu_spi.o : Lucida/lib_src/cpu_spi.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}cpu_timer.o : Lucida/lib_src/cpu_timer.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}cpu_twi.o : Lucida/lib_src/cpu_twi.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}cpu_uart.o : Lucida/lib_src/cpu_uart.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}cpu_util.o : Lucida/lib_src/cpu_util.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}MacroInit.o : Lucida/startup/MacroInit.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}startup.o : Lucida/startup/startup.s
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) -Wa,$(ASFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}pelco_app.o : Protocol/pelco_app.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}pelco_drv.o : Protocol/pelco_drv.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}spim_app.o : Protocol/spim_app.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}spim_drv.o : Protocol/spim_drv.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}spis_app.o : Protocol/spis_app.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}spis_drv.o : Protocol/spis_drv.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}usb_app.o : Protocol/usb_app.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}visca_app.o : Protocol/visca_app.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}visca_drv.o : Protocol/visca_drv.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}ae.o : Video/ae.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}ae_agc.o : Video/ae_agc.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}ae_aux.o : Video/ae_aux.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}ae_blc.o : Video/ae_blc.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}ae_core.o : Video/ae_core.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}ae_hall.o : Video/ae_hall.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}ae_iris.o : Video/ae_iris.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}ae_pwm.o : Video/ae_pwm.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}ae_sht.o : Video/ae_sht.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}awb.o : Video/awb.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}awb_aux.o : Video/awb_aux.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}awb_color.o : Video/awb_color.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}awb_core.o : Video/awb_core.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}demo.o : Video/demo.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}misc.o : Video/misc.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

${OBJDIR}video.o : Video/video.c
	@$(ECHO) 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"

